repos:
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.1
    hooks:
      - id: pylint
        name: pylint (l2gv2)
        entry: pylint
        language: system
        types: [python]
        files: ^l2gv2/.*\.py$
      - id: pylint
        name: pylint (tests)
        entry: pylint
        language: system
        types: [python]
        files: ^tests/.*\.py$