[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "l2gv2"
version = "0.0.1"
authors = [
  { name="Martin Lotz", email="martin.lotz@warwick.ac.uk" }
]
description = ""
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD 3-Clause License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/lotzma/L2Gv2"
"Bug Tracker" = "https://github.com/lotzma/L2Gv2/issues"