name: lint

on:
  push:
    branches: [ main ]
    paths:
    - 'l2gv2/**/*.py'
    - 'tests/**/*.py'
    - '.github/workflows/lint.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'l2gv2/**/*.py'
    - 'tests/**/*.py'
    - '.github/workflows/lint.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up nox
      uses: wntrblm/nox@2025.02.09
      with:
        python-versions: "3.10"
    - name: Run linting
      run: nox -s lint
