name: ruff

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ruff.yml'
      - 'l2gv2/**.py'
      - 'tests/**.py'
      - 'pyproject.toml'
  pull_request:
    paths:
      - '.github/workflows/ruff.yml'
      - 'l2gv2/**.py'
      - 'tests/**.py'
      - 'pyproject.toml'
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/ruff-action@v3
      run: make ruff-checks
