name: tests

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/tests.yml'
      - 'l2gv2/**.py'
      - 'tests/**.py'
      - 'requirements.txt'
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'l2gv2/**.py'
      - 'tests/**.py'
      - 'requirements.txt'
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install -r requirements.txt
    - name: Test with pytest
      run: |
        python3 -m pytest
