name: tests

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/tests.yml'
      - 'l2gv2/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'l2gv2/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Run tests
      run: make
    - name: Run notebooks
      run: make notebooks
