name: tests

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/tests.yml'
      - 'l2gv2/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'l2gv2/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up nox
      uses: wntrblm/nox@2025.02.09
      with:
        python-versions: "3.10"
    - name: Run tests
      run: nox -s tests
